### ISSUE TITLE
[FRONT] Criar front-end de cadastro

### ISSUE THREAD

**Issue by Lohann** [paft-inc/paft-microservices#26]
# Descrição
No projeto `frontend` crie um página simples com dois campos: **usuario** e **senha**, ao clicar nesse botão, a aplicação deve chamar o endpoint criado na tarefa #21 para cadastrar o usuário, e exibir a mensagem retornada.

Para fazer o front-end utilize HTML com qualquer outra tecnologia que tenha mais familiaridade (PyScript, ReactJS, VueJS, etc)..

# Critérios de aceitação
Supondo que aplicação esteja rodando em `localhost:3000`, ao executar o comando abaixo:
```bash
curl localhost:3000
```
A aplicação deve retornar:
status: `200`
headers: `Content-Type: text/html`
body: (obs: substituia o `conteúdo aqui`, pelo html do formulário de login)
```html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <title>PAFT Login</title>
</head>
<body>
    <h1>Login</h1>
    <div>conteudo aqui</div>
</body>
</html>
```

**Comment by Botelhomf** [comment]
- [ ] Criar Frontend de login conforme informações acima
- [ ] Testar funcionalidade
